### ISSUE TITLE
Right click on the web page is not working

### ISSUE THREAD

**Issue by Naveenv22** [sergueik/SWET#1]
Hi sergueik,

I have download the project and worked on it, seems like everything is working fine the sample tool box gets opened, and the browse get launched when the launch browser icon is clicked, also clicked on the inject icon and the script got injected, which can be viewed through the test env console, but when i perform right click on an element in  the web page i am not getting any form regarding the element, followed the exact steps as provided in git, but still i don't find any form while performing right click, 

kindly help me with a solution....

**Comment by sergueik** [comment]
Hello ,

The README.md was incorrect in the mouse action part. You need to use CTRL +  right click.

Note that in the current revision the application toolbar 'inject' button  action handler is running on a UI thread, and you have to click the application button every time after the element information from the page is collected and added to the breadcrump.

**Comment by Naveenv22** [comment]
Hi sergueik,

Yes now i got it, Thank you very much for your quick reply. i never expect your reply will be in quick time. Thank you very much for your support. 

Thanks,
Naveen.

**Comment by Naveenv22** [comment]
Hi sergueik,

The code is not detecting Tab change when using it on webpages like amazon etc. when we choose a product the website directs to a new tab so that we cannot able to inject the script in the current page the explore icon is disabled at that moment.

kindly please provide assistant on that 

Thanks,
Naveen

**Comment by Naveenv22** [comment]
Hi sergueik,

The code is not detecting Tab change when using it on webpages like amazon etc. when we choose a product the website directs to a new tab so that we cannot able to inject the script in the current page the explore icon is disabled at that moment.

kindly please provide assistant on that

Thanks,
Naveen

**Comment by sergueik** [comment]
Thanks for reporting this. Tracking of runaway browser currently is not very  powerful. Conversion of toolbar button listener to running in the background thread  would take some time.

**Comment by Naveenv22** [comment]
Hi.

I am facing an issue while trying to inject the script there was an unexcepted error denoting "org.openqa.selenium.WebDriverException: unknown error: Runtime. evaluate threw exception: SyntaxError: Invalid or unexpected token"

Could you help me why this is happening whether it is because of selenium or browser facts...

**Comment by sergueik** [comment]
HELLO Naveen 

Sorry for late reply

provide more information about the url of the page you getting the exception, please     On Monday, April 1, 2019, 4:54:51 AM EDT, Naveenv22 <notifications@github.com> wrote:  
 
 
Hi.

I am facing an issue while trying to inject the script there was an unexcepted error denoting "org.openqa.selenium.WebDriverException: unknown error: Runtime. evaluate threw exception: SyntaxError: Invalid or unexpected token"

Could you help me why this is happening whether it is because of selenium or browser facts...

**Comment by Naveenv22** [comment]
hey sergueik, actually the issue was with selenium driver version. I have
updated it to the latest and it works fine.

thankyou for your response :)


ThankYou,
Naveen
