### ISSUE TITLE
Cannot build the project - dependency resolution issue

### ISSUE THREAD

**Issue by zootyzoot** [sergueik/SWET#2]
The build script throws up an error:

Failed to execute goal on project swet: Could not resolve dependencies for project com.github.sergueik.swet:swet:jar:0.0.13-SNAPSHOT: Failed to collect dependenci
es at com.github.sergueik.jprotractor:skdf_jprotractor:jar:0.9-SNAPSHOT: Failed to read artifact descriptor for com.github.sergueik.jprotractor:skdf_jprotractor:jar:0.9-S
NAPSHOT: Could not transfer artifact com.github.sergueik.jprotractor:skdf_jprotractor:pom:0.9-SNAPSHOT from/to central (http://central.maven.org/maven2/): Connect to cent
ral.maven.org:80 [central.maven.org/127.42.0.2] failed: Connection refused: connect

**Comment by sergueik** [comment]
thanks for reporting -  not keping up with publishing  the dependnencies through sonatype. to resolve locally, need to do `maven install` of  `jprotractor` in https://github.com/sergueik/SKDF and this in turn may require installing the https://github.com/sergueik/jProtractor. I will look into publishing these  to sonatype repo 

https://oss.sonatype.org/content/repositories/snapshots/com/github/sergueik/

**Comment by sergueik** [comment]
bumped the dependencies version - please try building again
